// src/locales/zh.js
export default {
    app: {
        order: "排序",
        filter: "过滤",
        ascending: "升序",
        descending: "降序",
        selected: "选中",
    },
    theme: {
        title: "主题",
        light: "Light",
        dark: "Dark",
    },
    nav: {
        download: "下载",
        server: "服务器",
        search: "搜索",
        prefs: "选项",
        logs: "日志",
        about: "关于",
    },
    about: {
        stats: "统计信息",
    },
    dialogs: {
        ok: "确定",
        cancel: "取消",
    },
    ed2k: {
        no_link: "没有可以下载的链接",
        serv_recv: "服务器接收到",
        links_dot: "个链接。",
        links: "链接",
    },
    logs: {
        cat: "类别",
        clear_all_logs: "清空日志",
        autoscroll: "自滚动",
    },
    search: {
        please_select_files: "请选择要下载的文件",
        download_to: "下载到",
        name: "名称",
        size: "大小",
        sources: "来源",
        none: "不排序",
    },
    servers: {
        invalid_ipv4: "无效的 IPv4 地址",
        bootstrap: "引导",
        connect: "连接",
        disconnect_server: "断开服务器连接",
        disconnect_kad: "断开 KAD 连接",
        connect_kad: "连接 KAD 网络",
        disconnect: "断开连接",
        remove: "删除",
        confirmRemoveServer: "确定要删除服务器吗？",
        active: "已连接",
        action: "操作",
        name: "名称",
        address: "地址",
        description: "描述",
        users: "用户数",
        files: "文件数",
    },
    download: {
        task_action: "操作",
        copy_success: "已复制",
        copy_fail: "复制失败",
        pause: "暂停",
        resume: "恢复",
        cancel: "删除",
        priodown: "降低优先级",
        prioup: "增加优先级",
        copy_link: "复制链接",
        remove: "删除 ",
        tasks: " 个任务？",
        please_select_tasks: "请选择任务。",
        unsupported_cmd: "你想干啥:",
        name: "名称",
        cat: "类别",
        size: "大小",
        speed: "速度",
        prio: "优先级",
        status: "状态",
        complete: "完成度",
    },
    prefs: {
        logout: "注销",
        save: "保存",
        key: "键",
        value: "值",
        description: "描述（我也不懂这些选项是啥）",
        readonly: "(只读)",
        dtable: {
            nick: "Nickname",
            connection: {
                max_line_up_cap: "Max upload rate (for statistics only)",
                max_line_down_cap: "Max download rate (for statistics only)",
                max_up_limit: "Max upload rate",
                max_down_limit: "Max download rate",
                slot_alloc: "Slot allocation",
                tcp_port: "TCP port",
                udp_port: "UDP port",
                udp_dis: "Disable UDP connections",
                max_file_src: "Max sources per file",
                max_conn_total: "Max total connections (total)",
                autoconn_en: "Autoconnect at startup",
                reconn_en: "Reconnect when connection lost",
                network_ed2k: "Enable ED2K network",
                network_kad: "Enable Kademlia network",
            },
            files: {
                ich_en: "I.C.H. active",
                aich_trust: "AICH trusts every hash (not recommended)",
                new_files_paused: "Add files to download queue in pause mode",
                new_files_auto_dl_prio: "Added download files have auto priority",
                new_files_auto_ul_prio: "New shared files have auto priority",
                extract_metadata: "Extract metadata tags",
                alloc_full: "Alloc full disk space for .part files",
                check_free_space: "Check free space",
                min_free_space: "Minimum free space (Mb)",
            },
            webserver: {
                use_gzip: "Use gzip compression",
                autorefresh_time: "Page refresh interval",
            },
        },
    },
}
