FROM ghcr.nju.edu.cn/jjling2011/amule-m26:latest

# Add M26 web UI
COPY dist/M26/ /usr/share/amule/webserver/M26/

WORKDIR /home/amule

EXPOSE 4711/tcp 4712/tcp 4662/tcp 4665/udp 4672/udp

ENTRYPOINT ["/home/amule/entrypoint.sh"]
